version: '3.8'

services:
  # 운영 스프링 부트 API 서버 컨테이너만 실행합니다.
  catch-api:
    build:
      context: ../
      dockerfile: infra/Dockerfile
    container_name: catch-api-prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mariadb://${PROD_DB_HOST}:3306/${PROD_DB_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${PROD_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${PROD_DB_PASSWORD}
    restart: always