version: '3.8'

services:
  # 운영 스프링 부트 API 서버 컨테이너만 실행합니다.
  catch-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catch-api-prod
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - catch-redis
    restart: always

  catch-redis:
    image: redis:alpine
    container_name: catch-redis-prod
    ports:
      - "6379:6379"
    restart: always