spring:
  datasource:
    url: jdbc:mariadb://${PROD_DB_HOST}:3306/${PROD_DB_DATABASE}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - email
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:3600000} # 기본값 1시간
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:1209600000} # 기본값 14일